### ISSUE TITLE
Bug when announcing !

### ISSUE THREAD

**Issue by Royalphax** [Roytreo28/BungeeAnnounce#2]
```10:38:16 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@19fe4644, id=1, owner=fr.roytreo.bungeeannounce.BungeeAnnouncePlugin@346939bf, task=fr.roytreo.bungeeannounce.task.ScheduledAnnouncement@72a85671, delay=10000, period=3100000, running=true) encountered an exception
java.lang.NullPointerException
at fr.roytreo.bungeeannounce.BungeeAnnouncePlugin.announce(BungeeAnnouncePlugin.java:222)
at fr.roytreo.bungeeannounce.BungeeAnnouncePlugin.send(BungeeAnnouncePlugin.java:255)
at fr.roytreo.bungeeannounce.task.ScheduledAnnouncement.run(ScheduledAnnouncement.java:51)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
``` 
— _from[ josecuervo2016](https://www.spigotmc.org/threads/bungee-announce-1-8-1-9-1-10-1-11-1-12.80464/page-6#post-2620097)_

**Comment by Royalphax** [comment]
Done !
